# Generated by Django 2.0.1 on 2018-01-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendingMachine',
            fields=[
                ('machineCode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('activate_flag', models.BooleanField(default=True)),
                ('definition', models.TextField(verbose_name='Vending Machine Racks definition in JSON')),
            ],
        ),
    ]
